# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library.
# possible values are 'localtime', 'UTC', or a specific timezone name
# from python-dateutil, such as 'America/Chicago'
# timezone =

# max length of characters to use in "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be listed as revisions in the
# versions/ directory
# sourceless = false

# version location specification; this defaults
# to migrations/versions.  When using multiple version
# directories, separate the paths in space-delimited format.
# (e.g. version_locations = %(here)s/bar/versions %(here)s/bat/versions)
# version_locations = %(here)s/migrations/versions

# the REPL prompt; the default is >>>
# pyprompt = >>>

# version path separator; is typically ';' or ' '
# version_path_separator = ;

# set to 'true' to search for scripts in subdirectories
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5435/mindware_affiliates


[post_write_hooks]
# post_write_hooks allows scripts or Python functions to be run
# after generate-revision has been run. These functions can then
# modify the generated revision script to add extra information
# or apply code formatting.

# Example: apply black formatting to the generated revision script
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[logging]
# Logging configuration

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine.base.Engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
