"""Initial migration

Revision ID: d3ca5b0738da
Revises: 
Create Date: 2026-04-28 07:29:38.550901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ca5b0738da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('comissao', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AFFILIATE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('affiliates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('conta_bancaria', sa.String(length=100), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('codigo_afiliado', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'REJECTED', name='affiliatestatus'), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_afiliado'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lead_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('client_nome', sa.String(length=255), nullable=False),
    sa.Column('client_telefone', sa.String(length=50), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONVERTED', 'LOST', name='leadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('saldo_disponivel', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('saldo_pendente', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_ganho', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_levantado', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id')
    )
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('conta_bancaria', sa.String(length=100), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('notas_admin', sa.Text(), nullable=True),
    sa.Column('comprovativo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('lead_notification_id', sa.Uuid(), nullable=True),
    sa.Column('client_nome', sa.String(length=255), nullable=False),
    sa.Column('client_telefone', sa.String(length=50), nullable=False),
    sa.Column('valor_servico', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'REJECTED', name='commissionstatus'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('comprovativo_url', sa.String(length=500), nullable=True),
    sa.Column('comprovativo_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['lead_notification_id'], ['lead_notifications.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissions')
    op.drop_table('withdrawal_requests')
    op.drop_table('wallets')
    op.drop_table('notifications')
    op.drop_table('lead_notifications')
    op.drop_table('affiliates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('token_blacklist')
    op.drop_table('services')
    # ### end Alembic commands ###
